Review
DTsurkov/dirSync pull request #4
Opened 2022-07-18 09:39 UTC by DTsurkov

2022-07-19 07:40 UTC, ruheadshot requested changes
Давай сначала исправь что я уже нашел и потом я продолжу. А то тяжело разбираться

2022-07-19 07:40 UTC, ruheadshot commented on sync.py
> -
Отсутствует main()

2022-07-19 07:40 UTC, ruheadshot commented on sync.py
> -verboseprint = print if args.verbose else lambda *a, **k: None
Зачем это здесь?

2022-07-19 07:40 UTC, ruheadshot commented on sync.py
> -while(1):
Нет обработки прерывания. Например, ctrl+c

2022-07-19 07:40 UTC, ruheadshot commented on synchelper.py
> -    def addDirectory(self,directory):
Дикая каша из неформатированного кода
![image](https://user-images.githubusercontent.com/8456238/179489220-aa37d148-a86f-4a6d-b393-1094ce94ddf8.png)

2022-07-19 07:40 UTC, ruheadshot commented on synchelper.py
> -            items.put(item)
Нет синхронизации потоков

2022-07-19 07:40 UTC, ruheadshot commented on synchelper.py
> -            print("[Syncher] Starting item synchronization. [{0}]".format(time.strftime("%H:%M:%S")))
Наверное itemS - лог вводит в заблуждение.
Также для выведения каких-либо временнЫх меток лучше использовать единую обертку, а не хардкодить каждый раз. А еще лучше - использовать логгер. В нем и скоуп можно задать ([Syncher])

2022-07-19 07:40 UTC, ruheadshot commented on synchelper.py
> -                pass
Слишком общий exception, да еще и без какой-либо обработки ошибки и без коммента почему она не нужна - плохо

2022-07-19 07:40 UTC, ruheadshot commented on synchelper.py
> -                except IOError as e:
Других не может быть ошибок?

2022-07-19 07:40 UTC, ruheadshot commented on synchelper.py
> -                t.direction = 0
Что такое 0 в direction слишком неявно. Лучше использовать методы с говорящими названиями. Например, `setDirectionSynced()` или `setDirection(DIRECTION_SYNCED)`

UPD: интересно, что метод есть, но ты его не используешь

2022-07-19 07:40 UTC, ruheadshot commented on synchelper.py
> -                    pass
![image](https://user-images.githubusercontent.com/8456238/179687223-90b892c5-e23c-43d1-a725-105205ff9152.png)

2022-07-19 07:40 UTC, ruheadshot commented on synchelper.py
> -    def setDirection(self,Direction):
Никогда не называй переменные или параметры с большой буквы - это обозначение классов. Цифры, обозначающие direction нужно упаковать в константы и использовать их

2022-07-19 07:40 UTC, ruheadshot commented on synchelper.py
> -                    if dir == latest:
Здесь опционально, но погугли про тернарный оператор

2022-07-26 20:15 UTC, DTsurkov commented on sync.py
> -
done

2022-07-26 20:16 UTC, DTsurkov commented on sync.py
> -verboseprint = print if args.verbose else lambda *a, **k: None
Хотел вначале сделать вербоспринт через отдельную функцию, но передумал. Так что незачем. Выкинул)

2022-07-26 20:16 UTC, DTsurkov commented on sync.py
> -while(1):
Добавил

2022-07-26 20:17 UTC, DTsurkov commented on synchelper.py
> -    def addDirectory(self,directory):
сделал красивее (надеюсь, правильно понял понятие красоты)

2022-07-26 20:17 UTC, DTsurkov commented on synchelper.py
> -                pass
добавил объяснение и ловлю неожиданных эксепшенов

2022-07-26 20:18 UTC, DTsurkov commented on synchelper.py
> -                except IOError as e:
могут( поправил

2022-07-26 20:19 UTC, DTsurkov commented on synchelper.py
> -                t.direction = 0
Сделал эннум со значениями. Заюзал метод для сеттинга. Думал о методе для получения, но конкретно в моём случае не уверен, что он нужен...

2022-07-26 20:20 UTC, DTsurkov commented on synchelper.py
> -                    pass
сделал более читаемым

2022-07-26 20:23 UTC, DTsurkov commented on synchelper.py
> -    def setDirection(self,Direction):
поправил... В pep написано, что нужно именовать через символы "_" =( я пока не смирился и не исправил на такое именование...

2022-07-26 21:02 UTC, DTsurkov commented on synchelper.py
> -            print("[Syncher] Starting item synchronization. [{0}]".format(time.strftime("%H:%M:%S")))
Пока заюзал единую обертку в виде самопальной функции print в из самопальной лимбы prettyPrint.py.

2023-03-16 18:02 UTC, closed without merging

2023-03-16 20:29 UTC, ruheadshot commented
ЭхBest regards,Sergei GorodskoiOn 16. 3. 2023, at 19:02, DTsurkov ***@***.***> wrote:﻿
Closed #4.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>